server:
  port: 9001

spring:
  application:
    name: user-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    # eureka-server url
    service-url:
      defaultZone: http://localhost:8761/eureka